/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidades.EVeiculo;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NVeiculo;
import util.tipoabstrato.TipoAbstrato;

/**
 *
 * @author vitor
 */
public class TelaVeiculo extends javax.swing.JInternalFrame {

    private JDesktopPane principal;

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaVeiculo() {
        initComponents();
        listarVeiculo();
        listarTipoVeiculo();
    }

    public TelaVeiculo(JDesktopPane principal) {
        this();
        this.principal = principal;
    }

    private void limparCampos() {
        jTextFieldCODIGO.setText("");
        jTextFieldNOME.setText("");
        jTextFieldMODELO.setText("");
        jTextFieldCOR.setText("");
        jTextFieldPLACA.setText("");
        jTextFieldPESQUISAR.setText("");
    }

    private void listarVeiculo() {
        try {

            DefaultTableModel model = (DefaultTableModel) jTableLISTAVEICULO.getModel();
            model.setNumRows(0);
            model.setColumnCount(0);
            model.setColumnIdentifiers(new Object[]{
                "Código",
                "Nome",
                "Modelo",
                "Cor",
                "Placa",
                "Tipo de Veículo"
            });

            new NVeiculo().listar().forEachRemaining(listVeiculo -> {
                model.addRow(new Object[]{
                    listVeiculo.getCodigo(),
                    listVeiculo.getNome(),
                    listVeiculo.getModelo(),
                    listVeiculo.getCor(),
                    listVeiculo.getPlaca(),
                    listVeiculo.getTipoVeiculo().getDescricao()
                });
            });

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro na telaVeiculo, método listarVeiculo = " + e.getMessage());
        }
    }

    private void listarTipoVeiculo() {
        try {
            jComboBoxTIPOVEICULO.removeAllItems();
            for (String descricao : TipoAbstrato.getListaDeTipos()) {
                jComboBoxTIPOVEICULO.addItem(descricao);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na telaVeiculo, método listarTipoVeiculo = " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLISTAVEICULO = new javax.swing.JTable();
        jTextFieldPESQUISAR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonGRAVAR = new javax.swing.JButton();
        jTextFieldCODIGO = new javax.swing.JTextField();
        jTextFieldNOME = new javax.swing.JTextField();
        jButtonEXCLUIR = new javax.swing.JButton();
        jButtonNOVO = new javax.swing.JButton();
        jButtonBUSCAR = new javax.swing.JButton();
        jTextFieldMODELO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCOR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPLACA = new javax.swing.JTextField();
        jRadioButtonPLACA = new javax.swing.JRadioButton();
        jRadioButtonNOME = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxTIPOVEICULO = new javax.swing.JComboBox<>();
        jRadioButtonTIPO = new javax.swing.JRadioButton();

        setClosable(true);

        jTableLISTAVEICULO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLISTAVEICULO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLISTAVEICULOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLISTAVEICULO);

        jLabel1.setText("INFORME A SUA BUSCA DE ACORDO COM CHECKBOX:");

        jLabel3.setText("CÓDIGO:");

        jLabel4.setText("NOME:");

        jLabel5.setText("MODELO:");

        jButtonGRAVAR.setText("GRAVAR");
        jButtonGRAVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGRAVARActionPerformed(evt);
            }
        });

        jTextFieldCODIGO.setEditable(false);

        jButtonEXCLUIR.setText("EXCLUIR");
        jButtonEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEXCLUIRActionPerformed(evt);
            }
        });

        jButtonNOVO.setText("NOVO");
        jButtonNOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNOVOActionPerformed(evt);
            }
        });

        jButtonBUSCAR.setText("BUSCAR");
        jButtonBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBUSCARActionPerformed(evt);
            }
        });

        jLabel6.setText("COR:");

        jLabel7.setText("PLACA:");

        jRadioButtonPLACA.setText("PLACA");
        jRadioButtonPLACA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPLACAActionPerformed(evt);
            }
        });

        jRadioButtonNOME.setText("NOME");
        jRadioButtonNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNOMEActionPerformed(evt);
            }
        });

        jLabel8.setText("TIPO DE VEÍCULO:");

        jComboBoxTIPOVEICULO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButtonTIPO.setText("TIPO");
        jRadioButtonTIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTIPOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jTextFieldPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonPLACA)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonBUSCAR))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonNOME)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButtonTIPO)))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxTIPOVEICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jTextFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(116, 116, 116)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(jTextFieldMODELO)))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGRAVAR)
                                .addGap(55, 55, 55)
                                .addComponent(jButtonEXCLUIR)
                                .addGap(61, 61, 61)
                                .addComponent(jButtonNOVO)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldPLACA))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCOR, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(198, 198, 198)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNOME)
                            .addComponent(jRadioButtonTIPO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonPLACA))
                    .addComponent(jButtonBUSCAR))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxTIPOVEICULO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonGRAVAR)
                    .addComponent(jTextFieldMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNOVO)
                    .addComponent(jButtonEXCLUIR))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLISTAVEICULOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLISTAVEICULOMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableLISTAVEICULO.getModel();
        jTextFieldCODIGO.setEnabled(false);
        int selecionado = jTableLISTAVEICULO.getSelectedRow();

        if (model.getValueAt(selecionado, 0) != null) {
            jTextFieldCODIGO.setText(model.getValueAt(selecionado, 0).toString());
        }
        if (model.getValueAt(selecionado, 1) != null) {
            jTextFieldNOME.setText(model.getValueAt(selecionado, 1).toString());
        }
        if (model.getValueAt(selecionado, 2) != null) {
            jTextFieldMODELO.setText(model.getValueAt(selecionado, 2).toString());
        }
        if (model.getValueAt(selecionado, 3) != null) {
            jTextFieldCOR.setText(model.getValueAt(selecionado, 3).toString());
        }
        if (model.getValueAt(selecionado, 4) != null) {
            jTextFieldPLACA.setText(model.getValueAt(selecionado, 4).toString());
        }
        if (model.getValueAt(selecionado, 5) != null) {
            jComboBoxTIPOVEICULO.setSelectedItem(model.getValueAt(selecionado, 5).toString());
        }
    }//GEN-LAST:event_jTableLISTAVEICULOMouseClicked

    private void jButtonGRAVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGRAVARActionPerformed
        // TODO add your handling code here:
        try {
            String nome = jTextFieldNOME.getText();
            String modelo = jTextFieldMODELO.getText();
            String cor = jTextFieldCOR.getText();
            String placa = jTextFieldPLACA.getText();
            String tipoVeiculo = jComboBoxTIPOVEICULO.getSelectedItem().toString();
            int tipoVeiculoN = jComboBoxTIPOVEICULO.getSelectedIndex();

            String valor = jTextFieldCODIGO.getText();
            EVeiculo veiculo = new EVeiculo(nome, modelo, cor, placa,
                    TipoAbstrato.getInstance(tipoVeiculoN + 1));

            if (valor.equals("")) {
                new NVeiculo().salvar(veiculo, valor);
            } else {
                veiculo.setCodigo(Integer.parseInt(jTextFieldCODIGO.getText()));
                new NVeiculo().salvar(veiculo, valor);
            }

            listarVeiculo();

            limparCampos();

        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro na TelaVeiculo, botão gravar = " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonGRAVARActionPerformed

    private void jButtonEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXCLUIRActionPerformed
        // TODO add your handling code here:
        try {
            int codigo = Integer.parseInt(jTextFieldCODIGO.getText());
            String nome = jTextFieldNOME.getText();
            String modelo = jTextFieldMODELO.getText();
            String cor = jTextFieldMODELO.getText();
            String placa = jTextFieldMODELO.getText();
            String tipoVeiculo = jComboBoxTIPOVEICULO.getSelectedItem().toString();

            EVeiculo veiculo = new EVeiculo(codigo, nome, modelo, cor, placa, TipoAbstrato.getInstance(tipoVeiculo));

            new NVeiculo().excluir(veiculo);

            listarVeiculo();

            limparCampos();
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro na telaVeiculo, método excluir = " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonEXCLUIRActionPerformed

    private void jButtonNOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNOVOActionPerformed
        // TODO add your handling code here:
        limparCampos();
        listarVeiculo();
    }//GEN-LAST:event_jButtonNOVOActionPerformed

    private void jButtonBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBUSCARActionPerformed
        // TODO add your handling code here:
        try {
            String consulta = jTextFieldPESQUISAR.getText().toUpperCase();
            DefaultTableModel model = (DefaultTableModel) jTableLISTAVEICULO.getModel();
            model.setNumRows(0);

            if (jRadioButtonNOME.isSelected()) {

                new NVeiculo().consultaPorFiltro(true, consulta).forEachRemaining(listVeiculo -> {
                    model.addRow(new Object[]{
                        listVeiculo.getCodigo(),
                        listVeiculo.getNome(),
                        listVeiculo.getModelo(),
                        listVeiculo.getCor(),
                        listVeiculo.getPlaca(),
                        listVeiculo.getTipoVeiculo().getDescricao()
                    });
                });
                
            } else if (jRadioButtonPLACA.isSelected()) {

                new NVeiculo().consultaPorFiltro(false, consulta).forEachRemaining(listVeiculo -> {
                    model.addRow(new Object[]{
                        listVeiculo.getCodigo(),
                        listVeiculo.getNome(),
                        listVeiculo.getModelo(),
                        listVeiculo.getCor(),
                        listVeiculo.getPlaca(),
                        listVeiculo.getTipoVeiculo().getDescricao()
                    });
                });
                
            } else if (jRadioButtonTIPO.isSelected()) {
                TipoAbstrato
                        .getInstance(jTextFieldPESQUISAR.getText())
                        .getListaDeVeiculos().forEach(listVeiculo -> {
                   model.addRow(new Object[]{
                        listVeiculo.getCodigo(),
                        listVeiculo.getNome(),
                        listVeiculo.getModelo(),
                        listVeiculo.getCor(),
                        listVeiculo.getPlaca(),
                        listVeiculo.getTipoVeiculo().getDescricao()
                   });
               });
            } else {
                listarVeiculo();
            }

        } catch (SQLException ex) {
            //ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na TelaVeiculo, botão buscar = " + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonBUSCARActionPerformed

    private void jRadioButtonPLACAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPLACAActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonPLACA.isSelected()) {
            jRadioButtonNOME.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonPLACAActionPerformed

    private void jRadioButtonNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNOMEActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonNOME.isSelected()) {
            jRadioButtonPLACA.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonNOMEActionPerformed

    private void jRadioButtonTIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTIPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTIPOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBUSCAR;
    private javax.swing.JButton jButtonEXCLUIR;
    private javax.swing.JButton jButtonGRAVAR;
    private javax.swing.JButton jButtonNOVO;
    private javax.swing.JComboBox<String> jComboBoxTIPOVEICULO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonNOME;
    private javax.swing.JRadioButton jRadioButtonPLACA;
    private javax.swing.JRadioButton jRadioButtonTIPO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLISTAVEICULO;
    private javax.swing.JTextField jTextFieldCODIGO;
    private javax.swing.JTextField jTextFieldCOR;
    private javax.swing.JTextField jTextFieldMODELO;
    private javax.swing.JTextField jTextFieldNOME;
    private javax.swing.JTextField jTextFieldPESQUISAR;
    private javax.swing.JTextField jTextFieldPLACA;
    // End of variables declaration//GEN-END:variables
}
