/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidades.EMotorista;
import static apresentacao.TelaPrincipal.central;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NMotorista;

/**
 *
 * @author vitor
 */
public class TelaMotorista extends javax.swing.JInternalFrame {

    private JDesktopPane principal;

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaMotorista() {
        initComponents();
        listarMotorista();
    }

    public TelaMotorista(JDesktopPane principal) {
        this();
        this.principal = principal;
    }

    private void limparCampos() {
        jTextFieldCODIGO.setText("");
        jTextFieldNOME.setText("");
        jTextFieldTELEFONE.setText("");
        jTextFieldRUA.setText("");
        jTextFieldBAIRRO.setText("");
        jTextFieldCIDADE.setText("");
        jTextFieldCNH.setText("");
        jTextFieldPESQUISAR.setText("");
        jRadioButtonFEMININO.setSelected(false);
        jRadioButtonMASCULINO.setSelected(false);
    }

    private void listarMotorista() {
        try {

            DefaultTableModel model = (DefaultTableModel) jTableLISTAMOTORISTA.getModel();
            model.setNumRows(0);
            model.setColumnCount(0);
            model.setColumnIdentifiers(new Object[]{
                "Código",
                "Nome",
                "Telefône",
                "Sexo",
                "Rua",
                "Bairro",
                "Cidade",
                "CNH"
            });

            new NMotorista().listar().forEachRemaining(listMotorista -> {
                model.addRow(new Object[]{
                    listMotorista.getCodigo(),
                    listMotorista.getNome(),
                    listMotorista.getTelefone(),
                    listMotorista.getSexo(),
                    listMotorista.getRua(),
                    listMotorista.getBairro(),
                    listMotorista.getCidade(),
                    listMotorista.getCnh()
                });
            });

//            while(new NMotorista().listar().hasNext()){
//               EMotorista listMotorista = new NMotorista().listar().next();
//               model.addRow(new Object[]{
//                    listMotorista.getCodigo(),
//                    listMotorista.getNome(),
//                    listMotorista.getTelefone(),
//                    listMotorista.getSexo(),
//                    listMotorista.getRua(),
//                    listMotorista.getBairro(),
//                    listMotorista.getCidade(),
//                    listMotorista.getCnh()
//                });
//            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro na telaMotorista, método listarMotorista = " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLISTAMOTORISTA = new javax.swing.JTable();
        jTextFieldPESQUISAR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonGRAVAR = new javax.swing.JButton();
        jTextFieldCODIGO = new javax.swing.JTextField();
        jTextFieldNOME = new javax.swing.JTextField();
        jButtonEXCLUIR = new javax.swing.JButton();
        jButtonNOVO = new javax.swing.JButton();
        jButtonBUSCAR = new javax.swing.JButton();
        jTextFieldTELEFONE = new javax.swing.JTextField();
        jRadioButtonMASCULINO = new javax.swing.JRadioButton();
        jRadioButtonFEMININO = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCIDADE = new javax.swing.JTextField();
        jTextFieldBAIRRO = new javax.swing.JTextField();
        jTextFieldRUA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCNH = new javax.swing.JTextField();
        jRadioButtonNOME = new javax.swing.JRadioButton();
        jRadioButtonCNH = new javax.swing.JRadioButton();

        setClosable(true);

        jTableLISTAMOTORISTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLISTAMOTORISTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLISTAMOTORISTAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLISTAMOTORISTA);

        jLabel1.setText("INFORME A SUA BUSCA DE ACORDO COM CHECKBOX:");

        jLabel3.setText("CÓDIGO:");

        jLabel4.setText("NOME:");

        jLabel5.setText("TELEFONE:");

        jButtonGRAVAR.setText("GRAVAR");
        jButtonGRAVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGRAVARActionPerformed(evt);
            }
        });

        jTextFieldCODIGO.setEditable(false);

        jButtonEXCLUIR.setText("EXCLUIR");
        jButtonEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEXCLUIRActionPerformed(evt);
            }
        });

        jButtonNOVO.setText("NOVO");
        jButtonNOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNOVOActionPerformed(evt);
            }
        });

        jButtonBUSCAR.setText("BUSCAR");
        jButtonBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBUSCARActionPerformed(evt);
            }
        });

        jRadioButtonMASCULINO.setText("MASCULINO");
        jRadioButtonMASCULINO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMASCULINOActionPerformed(evt);
            }
        });

        jRadioButtonFEMININO.setText("FEMININO");
        jRadioButtonFEMININO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFEMININOActionPerformed(evt);
            }
        });

        jLabel6.setText("SEXO:");

        jLabel7.setText("RUA:");

        jLabel8.setText("BAIRRO:");

        jLabel9.setText("CIDADE:");

        jLabel10.setText("CNH:");

        jRadioButtonNOME.setText("NOME");
        jRadioButtonNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNOMEActionPerformed(evt);
            }
        });

        jRadioButtonCNH.setText("CNH");
        jRadioButtonCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCNHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNOME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTELEFONE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldRUA, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonGRAVAR)
                                            .addGap(53, 53, 53)
                                            .addComponent(jButtonNOVO))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(42, 42, 42)
                                    .addComponent(jButtonEXCLUIR)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonMASCULINO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonFEMININO))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonCNH)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonNOME)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonBUSCAR)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonNOME)
                    .addComponent(jButtonBUSCAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonCNH))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonMASCULINO)
                                    .addComponent(jRadioButtonFEMININO)
                                    .addComponent(jLabel6))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldRUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGRAVAR)
                    .addComponent(jButtonNOVO)
                    .addComponent(jButtonEXCLUIR))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(38, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLISTAMOTORISTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLISTAMOTORISTAMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableLISTAMOTORISTA.getModel();
        jTextFieldCODIGO.setEnabled(false);
        int selecionado = jTableLISTAMOTORISTA.getSelectedRow();

        if (model.getValueAt(selecionado, 0) != null) {
            jTextFieldCODIGO.setText(model.getValueAt(selecionado, 0).toString());
        }
        if (model.getValueAt(selecionado, 1) != null) {
            jTextFieldNOME.setText(model.getValueAt(selecionado, 1).toString());
        }
        if (model.getValueAt(selecionado, 2) != null) {
            jTextFieldTELEFONE.setText(model.getValueAt(selecionado, 2).toString());
        }
        if (model.getValueAt(selecionado, 3) != null) {
            if (model.getValueAt(selecionado, 3) == "MASCULINO") {
                jRadioButtonMASCULINO.isSelected();
            } else {
                jRadioButtonFEMININO.isSelected();
            }
        }
        if (model.getValueAt(selecionado, 4) != null) {
            jTextFieldRUA.setText(model.getValueAt(selecionado, 4).toString());
        }
        if (model.getValueAt(selecionado, 5) != null) {
            jTextFieldBAIRRO.setText(model.getValueAt(selecionado, 5).toString());
        }
        if (model.getValueAt(selecionado, 6) != null) {
            jTextFieldCIDADE.setText(model.getValueAt(selecionado, 6).toString());
        }
        if (model.getValueAt(selecionado, 7) != null) {
            jTextFieldCNH.setText(model.getValueAt(selecionado, 7).toString());
        }
    }//GEN-LAST:event_jTableLISTAMOTORISTAMouseClicked

    private void jButtonGRAVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGRAVARActionPerformed
        // TODO add your handling code here:
        try {
            String nome = jTextFieldNOME.getText();
            String telefone = jTextFieldTELEFONE.getText();
            String sexo = null;
            if (jRadioButtonFEMININO.isSelected()) {
                sexo = "FEMININO";
            } else {
                sexo = "MASCULINO";
            }
            String rua = jTextFieldRUA.getText();
            String bairro = jTextFieldBAIRRO.getText();
            String cidade = jTextFieldCIDADE.getText();
            String cnh = jTextFieldCNH.getText();
            String valor = jTextFieldCODIGO.getText();

            EMotorista motorista = new EMotorista(central);

            motorista.setNome(nome);
            motorista.setTelefone(telefone);
            motorista.setSexo(sexo);
            motorista.setRua(rua);
            motorista.setBairro(bairro);
            motorista.setCidade(cidade);
            motorista.setCnh(cnh);

            new NMotorista().salvar(motorista, valor);
            

            listarMotorista();

            limparCampos();

        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro na TelaMotorista, botão gravar = " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonGRAVARActionPerformed

    private void jButtonEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXCLUIRActionPerformed
        // TODO add your handling code here:
        try {
            int codigo = Integer.parseInt(jTextFieldCODIGO.getText());
            String nome = jTextFieldNOME.getText();
            String telefone = jTextFieldTELEFONE.getText();
            String sexo = null;
            if (jRadioButtonFEMININO.isSelected()) {
                sexo = "FEMININO";
            } else {
                sexo = "MASCULINO";
            }
            String rua = jTextFieldRUA.getText();
            String bairro = jTextFieldBAIRRO.getText();
            String cidade = jTextFieldCIDADE.getText();
            String cnh = jTextFieldCNH.getText();

            EMotorista motorista = new EMotorista(codigo, nome, telefone, sexo,
                    rua, bairro, cidade, cnh);

            new NMotorista().excluir(motorista);
            central.excluir(motorista);

            listarMotorista();

            limparCampos();
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro na telaMotorista, método excluir = " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonEXCLUIRActionPerformed

    private void jButtonNOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNOVOActionPerformed
        // TODO add your handling code here:
        limparCampos();
        listarMotorista();
    }//GEN-LAST:event_jButtonNOVOActionPerformed

    private void jButtonBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBUSCARActionPerformed
        // TODO add your handling code here:
        try {
            String consulta = jTextFieldPESQUISAR.getText();
            DefaultTableModel model = (DefaultTableModel) jTableLISTAMOTORISTA.getModel();
            model.setNumRows(0);
            if (jRadioButtonNOME.isSelected()) {

                new NMotorista().consultaPorFiltro(true, consulta).forEachRemaining(listMotorista -> {
                    model.addRow(new Object[]{
                        listMotorista.getCodigo(),
                        listMotorista.getNome(),
                        listMotorista.getTelefone(),
                        listMotorista.getSexo(),
                        listMotorista.getRua(),
                        listMotorista.getBairro(),
                        listMotorista.getCidade(),
                        listMotorista.getCnh()
                    });
                });

//                while (new NMotorista().consultaPorFiltro(true, consulta).hasNext()) {
//                    EMotorista listMotorista = new NMotorista().consultaPorFiltro(true, consulta).next();
//                    model.addRow(new Object[]{
//                        listMotorista.getCodigo(),
//                        listMotorista.getNome(),
//                        listMotorista.getTelefone(),
//                        listMotorista.getSexo(),
//                        listMotorista.getRua(),
//                        listMotorista.getBairro(),
//                        listMotorista.getCidade(),
//                        listMotorista.getCnh()
//                    });
//                }
            } else if (jRadioButtonCNH.isSelected()) {

                new NMotorista().consultaPorFiltro(false, consulta).forEachRemaining(listMotorista -> {
                    model.addRow(new Object[]{
                        listMotorista.getCodigo(),
                        listMotorista.getNome(),
                        listMotorista.getTelefone(),
                        listMotorista.getSexo(),
                        listMotorista.getRua(),
                        listMotorista.getBairro(),
                        listMotorista.getCidade(),
                        listMotorista.getCnh()
                    });
                });

//                while (new NMotorista().consultaPorFiltro(false, consulta).hasNext()) {
//                    EMotorista listMotorista = new NMotorista().consultaPorFiltro(false, consulta).next();
//                    model.addRow(new Object[]{
//                        listMotorista.getCodigo(),
//                        listMotorista.getNome(),
//                        listMotorista.getTelefone(),
//                        listMotorista.getSexo(),
//                        listMotorista.getRua(),
//                        listMotorista.getBairro(),
//                        listMotorista.getCidade(),
//                        listMotorista.getCnh()
//                    });
//                }
            } else {
                listarMotorista();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na TelaMotorista, botão buscar = " + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonBUSCARActionPerformed

    private void jRadioButtonMASCULINOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMASCULINOActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonMASCULINO.isSelected()) {
            jRadioButtonFEMININO.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonMASCULINOActionPerformed

    private void jRadioButtonFEMININOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFEMININOActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonFEMININO.isSelected()) {
            jRadioButtonMASCULINO.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonFEMININOActionPerformed

    private void jRadioButtonNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNOMEActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonNOME.isSelected()) {
            jRadioButtonCNH.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonNOMEActionPerformed

    private void jRadioButtonCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCNHActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonCNH.isSelected()) {
            jRadioButtonNOME.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonCNHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBUSCAR;
    private javax.swing.JButton jButtonEXCLUIR;
    private javax.swing.JButton jButtonGRAVAR;
    private javax.swing.JButton jButtonNOVO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCNH;
    private javax.swing.JRadioButton jRadioButtonFEMININO;
    private javax.swing.JRadioButton jRadioButtonMASCULINO;
    private javax.swing.JRadioButton jRadioButtonNOME;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLISTAMOTORISTA;
    private javax.swing.JTextField jTextFieldBAIRRO;
    private javax.swing.JTextField jTextFieldCIDADE;
    private javax.swing.JTextField jTextFieldCNH;
    private javax.swing.JTextField jTextFieldCODIGO;
    private javax.swing.JTextField jTextFieldNOME;
    private javax.swing.JTextField jTextFieldPESQUISAR;
    private javax.swing.JTextField jTextFieldRUA;
    private javax.swing.JTextField jTextFieldTELEFONE;
    // End of variables declaration//GEN-END:variables
}
